version: "3"
services:
#  web:
  #    build: app
  #    restart: always
  #    ports:
  #      - "80:8080"
  #    depends_on:
  #      - api
  api:
    build: server
    restart: always
    ports:
      - "8081:8081"
    environment:
      DATA_BASE_HOST: db
    depends_on:
      - db
  db:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_USER: billow
      MYSQL_PASSWORD: billow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    volumes:
      - "./db:/var/lib/mysql"
