version: "3"
services:
  web:
    build: app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: serve4j
    restart: always
    ports:
      - "8081:8081"
    environment:
      DATA_BASE_HOST: db
    depends_on:
      - db
  db:
    build: db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    volumes:
      - ./data:/var/lib/mysql
    command: --innodb-flush-method=fsync
