version: "3"
services:
  web:
    build: app
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: server
    depends_on:
      - db
  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: root
