version: "3"
services:
  front-end:
    build: front-end
    restart: always
    ports:
      - "80:80"
    depends_on:
      - back-end
  back-end:
    build: back-end
    restart: always
    ports:
      - "8090:8090"
    environment:
      DATA_BASE_HOST: database
    volumes:
      - ./upload:/upload-dir
    depends_on:
      - database
  database:
    build: db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vx01
    volumes:
      - ./data:/var/lib/mysql
    command: --innodb-flush-method=fsync
