spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${DATA_BASE_HOST}:3306/cms?useSSL=false&allowPublicKeyRetrieval=true
  data:
    rest:
      base-path: /api
server:
  port: 8081
