POST http://localhost:8081/api/posts
Cache-Control: no-cache
Content-Type: application/json

{
  "title": "d",
  "content": "d",
  "category": "news"
}

###

GET http://localhost:8081/api/posts
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8081/api/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
